---
- hosts: all
  vars:
    proxy_env:
      LC_ALL: en_US.UTF-8
      LC_LCTYPE: en_US.UTF-8
      LC_MESSAGES: POSIX
    rvm1_rubies:
      - 'ruby-2.1.0'
    rvm1_rvm_check_for_updates: false
    rvm1_gpg_key_server: '213.133.103.71'

  roles:
    - { role: rvm_io.rvm1-ruby, tags: ruby, sudo: True }
    - { role: ANXS.erlang, tags: erlang, sudo: True, erlang_version: "17.4" }

  tasks:
    - name: install ansible modules requirements
      apt: pkg={{ item }} state=installed update_cache=yes cache_valid_time=3600
      sudo: true
      with_items:
        - python-psycopg2
        - python-pycurl
        - python-apt
        - curl
        - git
        - ruby-dev
        - gcc

    - name: install fpm
      sudo: True
      gem: name=fpm version=1.3.3 state=present user_install=no

    - name: symlink resm path
      file: src=/vagrant dest=~/resm state=link

    - name: install dependencies
      shell: make chdir=~/resm
